<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'PHPGoogleChart\\GoogleChart' => $baseDir . '/src/GoogleChart.php',
    'PHPGoogleChart\\GoogleChartColumn' => $baseDir . '/src/GoogleChartColumn.php',
    'PHPGoogleChart\\GoogleChartLine' => $baseDir . '/src/GoogleChartLine.php',
    'PHPGoogleChart\\GoogleChartPie' => $baseDir . '/src/GoogleChartPie.php',
);
